apiVersion: v1
kind: Service
metadata:
  name: infnet-guia-service
spec:
  type: NodePort
  selector:
    app: infnet-guia
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 30036  # Porta exposta no cluster
